//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCV_Class_Library
{
    using System;
    using System.Collections.Generic;
    
    public partial class HCVPatient
    {
        public short ID { get; set; }
        public string HealthCardNumber { get; set; }
        public string VCode { get; set; }
        public string PostalCode { get; set; }
    }
}
